name: Pawn Compiler

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'

  pull_request:
    types: [opened, reopened, synchronize]

  release:
    types: [published]
    tags:
      - "v*.*.*"

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.declare_sha.outputs.sha }}
      semver: ${{ steps.declare_sha.outputs.semver }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Parse SemVer string (release)
        id: semver_parser
        if: |
          github.event_name == 'release' &&
          github.event.action == 'published' &&
          startsWith(github.ref, 'refs/tags/')
        uses: booxmedialtd/ws-action-parse-semver@v1
        with:
          input_string: ${{ github.ref }}
          version_extractor_regex: '\/v(.*)$'
      
      - name: Declare SHA & package name
        id: declare_sha
        shell: bash
        run: |
          SHA=$(git rev-parse --short HEAD)
          echo "COMMIT_SHA=${SHA}" >> $GITHUB_ENV
          echo "::set-output name=sha::$SHA"
          echo "::set-output name=semver::${{ steps.semver_parser.outputs.fullversion }}"

      - name: Setup AMXXPawn Compiler
        uses: wopox1337/setup-amxxpawn@master
        with:
          version: "1.10.5461"

      - name: Setup ReAPI includes
        env:
          REPO: "s1lentq/reapi"
        run: |
          mkdir -p dep/reapi
          cd dep/reapi
          curl \
            --silent \
            https://api.github.com/repos/$REPO/releases/latest | \
            grep "browser_download_url" | \
            grep -Eo 'https://[^\"]*' | \
            xargs wget
          7z x *.zip
          echo "REAPI_INCLUDE_PATH=$(pwd)/addons/amxmodx/scripting/include" >> $GITHUB_ENV

      - name: Move SMA files
        run: |
          mkdir addons
          mv cstrike/addons/* -t addons/

      - name: Compile AMXX plugins
        working-directory: addons/amxmodx/scripting/
        env:
          REAPI_INCLUDE: ${{env.REAPI_INCLUDE_PATH}}
        run: |
          mkdir ../plugins/
          for sourcefile in *.sma;
          do
            amxxfile="`echo $sourcefile | sed -e 's/\.sma$/.amxx/'`"
            echo -n "Compiling $sourcefile ... "
            amxxpc $(basename $sourcefile) -i"include" -i"$REAPI_INCLUDE" -o"../plugins/$(basename $amxxfile)"
          done
          
      - name: Move compiled files to publish
        run: |
          mkdir publish
          mv addons/ -t publish/

      - name: Move resources files to publish
        run: |
          mkdir resources
          rsync -av --exclude='addons' cstrike/ resources/

      - name: Deploy plugins artifacts
        uses: actions/upload-artifact@v3
        with:
          name: TTT-Plugins-${{ env.COMMIT_SHA }}
          path: publish/*

      - name: Deploy resources artifacts
        uses: actions/upload-artifact@v3
        with:
          name: TTT-Resources-${{ env.COMMIT_SHA }}
          path: resources/*

  publish:
    name: "Publish"
    runs-on: ubuntu-latest
    needs: [build]
    
    steps:
      - name: Deploying plugins artifacts
        uses: actions/download-artifact@v3
        with:
          name: TTT-Plugins-${{needs.build.outputs.sha}}

      - name: Deploying resources artifacts
        uses: actions/download-artifact@v3
        with:
          name: TTT-Resources-${{needs.build.outputs.sha}}

      - name: Packaging files
        id: packaging-job
        if: |
          github.event_name == 'release' &&
          github.event.action == 'published' &&
          startsWith(github.ref, 'refs/tags/')
        run: |
          7z a -mm=Deflate -mfb=258 -mpass=15 -r TTT-Plugins-v${{needs.build.outputs.semver}}.zip addons/
          7z a -mm=Deflate -mfb=258 -mpass=15 -r TTT-Resources-v${{needs.build.outputs.semver}}.zip resources/
        
      - name: Publish artifacts
        uses: softprops/action-gh-release@v1
        id: publish-job
        if: |
          startsWith(github.ref, 'refs/tags/') &&
          steps.packaging-job.outcome == 'success'
        with:
          files: |
            *.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        